apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: migoperators.operators.riskfuel.com
spec:
  group: operators.riskfuel.com
  names:
    kind: MigOperator
    listKind: MigOperatorList
    plural: migoperators
    singular: migoperator
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
    subresources:
      status: {}
