---
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-mig-operator-daemonset-sa
  namespace: {{ .Values.deployNamespace }}
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mig-operator-psp-crb
  namespace: {{ .Values.deployNamespace }}
subjects:
- kind: ServiceAccount
  name: k8s-mig-operator-daemonset-sa
  namespace: {{ .Values.deployNamespace }}
roleRef:
  kind: ClusterRole
  name: k8s-mig-operator-daemonset-psp-role
  apiGroup: rbac.authorization.k8s.io
---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mig-operator-daemonset-role
rules:
- apiGroups: ["operators.riskfuel.com"]
  resources: 
    - migoperators
  verbs:
    - get
    - list
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mig-operator-crb
  namespace: {{ .Values.deployNamespace }}
subjects:
- kind: ServiceAccount
  name: k8s-mig-operator-daemonset-sa
  namespace: {{ .Values.deployNamespace }}
roleRef:
  kind: ClusterRole
  name: k8s-mig-operator-daemonset-role
  apiGroup: rbac.authorization.k8s.io
---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mig-operator-daemonset-gen-role
rules:
- apiGroups: [""]
  resources: 
    - nodes
    - pods
  verbs:
    - get
    - list
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mig-operator-gen-crb
  namespace: {{ .Values.deployNamespace }}
subjects:
- kind: ServiceAccount
  name: k8s-mig-operator-daemonset-sa
  namespace: {{ .Values.deployNamespace }}
roleRef:
  kind: ClusterRole
  name: k8s-mig-operator-daemonset-gen-role
  apiGroup: rbac.authorization.k8s.io
---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mig-operator-daemonset-del-role
rules:
- apiGroups: [""]
  resources: 
    - pods
  verbs:
    - delete
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mig-operator-del-crb
  namespace: {{ .Values.deployNamespace }}
subjects:
- kind: ServiceAccount
  name: k8s-mig-operator-daemonset-sa
  namespace: {{ .Values.deployNamespace }}
roleRef:
  kind: ClusterRole
  name: k8s-mig-operator-daemonset-del-role
  apiGroup: rbac.authorization.k8s.io
