apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mig-operator-daemon
  namespace: {{ .Values.deployNamespace }}
spec:
  selector:
    matchLabels:
      name: mig-operator-daemon
  template:
    metadata:
      labels:
        name: mig-operator-daemon
    spec:
      hostPID: true
      hostIPC: true
      
      serviceAccountName: k8s-mig-operator-daemonset-sa

      nodeSelector:
        nvidia.com/gpu.product: "A100-SXM4-40GB"

      containers:
      
      - image: {{ .Values.image }}
        imagePullPolicy: Always
        name: mig-operator
        securityContext:
          privileged: true
        env:
        - name: OPERATOR_NAME
          value: {{ .Values.operatorName }}
        - name: OPERATOR_NAMESPACE
          value: {{ .Values.operatorNamespace }}
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: ALLOW_NODE_RESET
          {{ if .Values.allowNodeReset }}
          value: "True"
          {{ else }}
          value: "False" 
          {{ end }}
        - name: DRY_RUN
          {{ if .Values.dryRun }}
          value: "True"
          {{ else }}
          value: "False" 
          {{ end }}
        - name: NVIDIA_MIG_MONITOR_DEVICES
          value: all
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        volumeMounts:
          - name: dmi-product-name
            mountPath: "/sys/class/dmi/id/product_name"
          {{ if .Values.allowNodeReset }}
          - mountPath: "/var/app-secret"
            name: ssh-key
            readOnly: true
          {{ end }}
      volumes:
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
        {{ if .Values.allowNodeReset }}
        - name: ssh-key
          secret:
            secretName: {{ .Values.sshSecretName }}
        {{ end }}
