FROM ubuntu:18.04 as cienv

RUN apt-get update && \
    apt-get -y install apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common && \
    curl -fsSL https://download.docker.com/linux/$(. /etc/os-release; echo "$ID")/gpg > /tmp/dkey; apt-key add /tmp/dkey && \
    add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/$(. /etc/os-release; echo "$ID") \
        $(lsb_release -cs) \
        stable" && \
    apt-get update && \
    apt-get -y install docker-ce

RUN apt-get update && apt-get install make

# Install the operator-sdk
ENV RELEASE_VERSION=v0.19.1

RUN curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
RUN curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/ansible-operator-${RELEASE_VERSION}-x86_64-linux-gnu
RUN curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/helm-operator-${RELEASE_VERSION}-x86_64-linux-gnu

RUN chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu \
    && mkdir -p /usr/local/bin/ \
    && cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk \
    && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu

RUN chmod +x ansible-operator-${RELEASE_VERSION}-x86_64-linux-gnu \
    && mkdir -p /usr/local/bin/ \
    && cp ansible-operator-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/ansible-operator \
    && rm ansible-operator-${RELEASE_VERSION}-x86_64-linux-gnu

RUN chmod +x helm-operator-${RELEASE_VERSION}-x86_64-linux-gnu \
    && mkdir -p /usr/local/bin/ \
    && cp helm-operator-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/helm-operator \
    && rm helm-operator-${RELEASE_VERSION}-x86_64-linux-gnu
