---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mig-instance-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mig-instance-operator
  template:
    metadata:
      labels:
        name: mig-instance-operator
    spec:
      serviceAccountName: mig-instance-operator
      containers:
        - name: mig-instance-operator
          image: "riskfuel/mig-operator:latest"
          imagePullPolicy: "Always"
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mig-instance-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
          livenessProbe:
            httpGet:
              path: /healthz
              port: 6789
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"

      volumes:
        - name: runner
          emptyDir: {}
