apiVersion: operators.riskfuel.com/v1alpha1
kind: MigOperator
metadata:
  name: example-mig-operator-auto
  namespace: default
spec:
  nodes:
    # hostname of node
    dl13:

      remote_user: addison
      # if not specified, features like toggling mig
      # or switching strategies wont be available
      secretName: migoperator-secret

      devices:
      - gpu: 7
        migEnabled: true
        gpuInstances:
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        - gpu_instance_profile: 7g.40gb
          compute_instances:
          - 1c.7g.40gb
          - 1c.7g.40gb
        # - gpu_instance_profile: 2g.10gb
        #   compute_instances: [2c]
        # - gpu_instance_profile: 1g.5gb
        #   compute_instances: [1c]
