apiVersion: operators.riskfuel.com/v1alpha1
kind: MigOperator
metadata:
  name: example-mig-operator-auto
  namespace: default
spec:
  nodes:
    # hostname of node
    dl13:
      devices:
      # Test multiple MIG single GPU
      - gpu: 0
        gpu_instances:
        # Options: 7g.40GB, 4g.20GB, 3g.20GB, 2g.10GB, 1g.5GB
        # Test multiple CI single GI
        - gpu_instance_profile: 3g.20GB
          compute_instances: [1c, 2c]
        - gpu_instance_profile: 2g.10GB
          compute_instances: [2c]
        - gpu_instance_profile: 1g.5GB
          compute_instances: [1c]
      # Test single CI on single GI 
      - gpu: 1
        gpu_instances:
        - gpu_instance_profile: 7g.20GB
          compute_instances: [7c]
      # Test an invalid configuration
      - gpu: 2
        gpu_instances:
        - gpu_instance_profile: 4g.20GB
          compute_instances: [4c]
        - gpu_instance_profile: 4g.20GB
          compute_instances: [4c]
