apiVersion: operators.riskfuel.com/v1alpha1
kind: MigOperator
metadata:
  name: example-mig-operator
  namespace: kube-system # set to namespace specified when installing
spec:
  nodes:
    # hostname of node
    <hostname>:

      remote_user: <your-user-name>

      # if not specified, features like toggling mig
      # or switching strategies wont be available
      secretName: migoperator-secret

      # Options for MIG instance profiles: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
      # Options for compute instance profiles: 7g.40gb, 4c.xg.ygb, 3c.xg.ygb, 2c.xg.ygb, 1c.xg.ygb
      # x denotes the compute allocation, and y denotes the memory allocation for the GPU instance
      devices:
      - gpu: 0
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 1
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 2
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 3
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 4
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 5
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 6
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
      - gpu: 7
        migEnabled: True
        # Options: 7g.40gb, 4g.20gb, 3g.20gb, 2g.10gb, 1g.5gb
        # Test multiple CI single GI
        gpuInstances:
        - profile: 4g.20gb
          computeInstances:
          - 1c.4g.20gb
          - 1c.4g.20gb
