- hosts: 127.0.0.1
  connection: local
  no_log: true
  tasks:
  
  - name: mkdir .ssh
    shell: mkdir /root/.ssh
    # register: out
    no_log: true

  - name: copy ssh-key
    shell: cp /var/app-secret/ssh-privatekey /root/.ssh/id_rsa
    # register: out
    no_log: true
  
  - name: update key perms
    shell: chmod 400 /root/.ssh/id_rsa
    # register: out
    no_log: true

  # - debug: var=out.stdout_lines
