# sec 11.1: https://docs.nvidia.com/dgx/pdf/dgxa100-user-guide.pdf
- hosts: all
  vars_files:
    - ./vars.yml
  remote_user: "{{ remote_user }}"
  tasks:

  - name: start services
    shell: |
      sudo systemctl start nvsm
      sudo systemctl start dcgm
    # register: out
    no_log: true

   # Permissions
  - name: grant user permissions to manage MIG instances
    file:
      path: "{{ item }}"
      owner: root
      group: root
      mode: '0444'
    with_items:
      - /proc/driver/nvidia/capabilities/mig/config
      - /proc/driver/nvidia/capabilities/mig/monitor
    tags: enable, never
  # - debug: var=out.stdout_lines
