name: bermudan test suite
on: 
  push:
    branches:
      - master
    paths:
    - 'roles/**'
    - '.github/workflows/deploy-operator.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Authenticate with dockerhub
      #   run: |
      #     echo "${{ secrets.DOCKER_TOKEN }}" | docker login --username addyvan --password-stdin

      # - name: Pull img
      #   run: |
