name: Deploy helm chart
on: 
  push:
    branches:
      - master
    paths:
    - '.github/workflows/deploy-chart.yml'
    - 'version'
jobs:
  deploy-mig-daemon-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: 'master'

      - name: Install tools
        run: |
          helm version
          echo "Installing chart-releaser..."
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v0.2.1/chart-releaser_0.2.1_linux_amd64.tar.gz | tar xzf -
          sudo mv cr /bin/cr
      
      - name: Release
        run: |
          export GIT_USERNAME=riskfuel
          export GIT_EMAIL=${{ secrets.GIT_EMAIL }}
          export CH_TOKEN=${{ secrets.GIT_TOKEN }}
          export GIT_REPOSITORY_NAME=k8s-mig-operator
          export GIT_REPOSITORY_URL=https://github.com/riskfuel/k8s-mig-operator
          
          version=$(cat version)
          
          helm package ./deployments/chart --destination .deploy
          cr upload ./deployments/chart --owner $GIT_USERNAME -r $GIT_REPOSITORY_NAME --token $CH_TOKEN -p .deploy
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'
          clean: false
          
      - name: Update chart index
        run: |
          cr index -i ./index.yaml -p .deploy --owner $GIT_USERNAME --repo $GIT_REPOSITORY_NAME
          git add index.yaml
          git commit -m "release $version"
          git push origin gh-pages
