name: Deploy helm chart
on: 
  push:
    branches:
      - master
    paths:
    - '.github/workflows/deploy-chart.yml'
    - 'deployments/chart/**'
    - 'version'
jobs:
  deploy-mig-daemon-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          ref: 'master'

      - name: Install tools
        run: |
          helm version
          echo "Installing chart-releaser..."
          curl -sSL https://github.com/helm/chart-releaser/releases/download/v0.2.1/chart-releaser_0.2.1_linux_amd64.tar.gz | tar xzf -
          sudo mv cr /bin/cr
      
      - name: Release
        run: |
          export GIT_EMAIL=${{ secrets.GIT_EMAIL }}
          export CH_TOKEN=${{ secrets.GIT_TOKEN }}
          export GIT_REPOSITORY_URL=https://github.com/riskfuel/k8s-mig-operator
          
          version=$(cat version)
          
          helm package --version=$version ./deployments/chart --destination .deploy
          cr upload ./deployments/chart --owner riskfuel -r k8s-mig-operator --token $CH_TOKEN -p .deploy || echo "$version already exists"
      
      - name: Checkout gh-pages branch
        uses: actions/checkout@v1
        with:
          ref: 'gh-pages'
          clean: false
          
      - name: Update chart index
        run: |
          cr index -i ./index.yaml -p .deploy --owner riskfuel --repo k8s-mig-operator || echo "index.yaml did not change"
          git add index.yaml
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ secrets.GIT_USER }}
          git commit -m "release $version" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          branch: gh-pages
