name: Deploy mig daemon image
on: 
  push:
    branches:
      - master
    paths:
    - 'src/**'
    - "requirements.txt"
    - "Dockerfile"
    - '.github/workflows/deploy-operator.yml'
jobs:
  deploy-mig-daemon-img:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: crazy-max/ghaction-docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build docker image
        run: |
          DOCKER_IMAGE=riskfuel/k8s-mig-operator:$(cat version)
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --tag ${DOCKER_IMAGE} \
            --output "type=docker" \
            .
      
      - name: push docker image
        run: |
          docker push riskfuel/k8s-mig-operator:$(cat version)
      