name: run test suite
on: 
  push:
    paths:
    - 'tests/**'
    - 'src/**'
    - '.github/workflows/run-tests.yml'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest

      - name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build image
        run: |
          version=$(cat version)
          DOCKER_IMAGE=riskfuel/k8s-mig-operator:$version
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/amd64 \
            --tag ${DOCKER_IMAGE} \
            --output "type=docker" \
            .

      - name: Run tests
        run: |
          version=$(cat version)
          DOCKER_IMAGE=riskfuel/k8s-mig-operator:$version
          docker tag ${DOCKER_IMAGE} mig-operator-ci-shell
          docker-compose run test
