apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mig-operator-daemon
  namespace: default
spec:
  selector:
    matchLabels:
      name: mig-operator-daemon
  template:
    metadata:
      labels:
        name: mig-operator-daemon
    spec:
      hostPID: true
      hostIPC: true
      
      serviceAccountName: k8s-mig-operator-daemonset-sa

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            # - matchExpressions:
            #   - key: nvidia.com/mig.strategy
            #     operator: In
            #     values:
            #     - mixed
            #     - single
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - dl13

      containers:
      
      - image: riskfuel/mig-operator-test:v0.0.1
        imagePullPolicy: Always
        name: mig-operator
        securityContext:
          privileged: true
        env:
        - name: PYTHONUNBUFFERED
          value: "0"
        - name: NVIDIA_MIG_MONITOR_DEVICES
          value: all
        - name: ANSIBLE_HOST_KEY_CHECKING
          value: "False"
        volumeMounts:
          - name: dmi-product-name
            mountPath: "/sys/class/dmi/id/product_name"
          - mountPath: "/var/app-secret"
            name: ssh-key
            readOnly: true
      volumes:
        - name: dmi-product-name
          hostPath:
            path: "/sys/class/dmi/id/product_name"
        - name: ssh-key
          secret:
            secretName: migoperator-secret
