---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: k8s-mig-operator-psp
  namespace: default
spec:
  privileged: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*'
---
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-mig-operator-daemonset-sa
  namespace: default
---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-mig-operator-daemonset-role
rules:
- apiGroups: ["operators.riskfuel.com"]
  resources: 
    - migoperators
    - podsecuritypolicies
  verbs:
    - use
    - get
    - list
  resourceNames:
  - psp:k8s-mig-operator-psp
---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-mig-operator-crb
subjects:
- kind: ServiceAccount
  name: k8s-mig-operator-daemonset-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: k8s-mig-operator-daemonset-role
  apiGroup: rbac.authorization.k8s.io
